### ISSUE TITLE
Rename get_num_rows()?

### ISSUE THREAD

**Issue by mesca** [OpenBCI/brainflow#115]
The method name is confusing, should not it be called `get_num_cols()` or `get_num_channels()`?

**Comment by Andrey1994** [comment]
get_num_cols is definitely wrong because in returned 2d array its rows, format is channels x number_of_data_points

I was thinking about get_num_channels instead get_num_rows but choosed "rows" because this array contains not only channel data, there are timestamps which are not streamed by the board usually, some additional info and so on

And if we rename it now it will be API breaking change and I dont want to do such changes without big reason for it because it will break all applications on top of it
