### ISSUE TITLE
[RFC] best option to release libraries

### ISSUE THREAD

**Issue by Andrey1994** [OpenBCI/brainflow#6]
It's just a request for comments.
**Problem: For now we commit all compiled libraries directly to github. This approach is very user friendly but not developer friendly**
Main benefit of doing so - user can run
```
git clone https://github.com/OpenBCI/brainflow
cd brainflow && cd python-package
pip install .
```
**And the same for all bindings, so users don't need to compile libraries by themselfs and they should not care about cmake, visual studio and so on, everything just works and it's perfect from user perspective. And I suppose that users expect it, if they see setup.py file or pom.xml it's a valid guess just run:**
```
python setup.py install
mvn package # and so on, for all bindings
```
Moreover  they can do so for current Python SDK!

But it's not comfortable from developer's perspective, we need to keep the code and compiled libraries up to date and match each other, so for each commit to core module of this library we need to build windows version, linux version and in future mac, probably we will need to build 32bit versions as well. And it leads to repo's size increasing 
And I wanna get rid of this development pipeline.

So my first question is:
**Is it okay to force users to compile it?**
It's pretty easy to compile it for linux and should be easy for Mac but for windows you need to download and install Visual Studio(~20GB) and users have to be aware of cmake and visual studio. *And I doubt that data scientists and domain researchers will do it, specially on windows*

Another question:
**If we can not force them to compile libraries can we provide them another option to install brainflow(it should be easy to use!).**

Possible solutions: 

- we can configure pipelines to compile, build bindings and release package to Maven/CRAN/PYPI for each commit or nightly builds.(We can call package smth like brainflow-dev, brainflow-latest or brainflow-nightly). This approach will allows users to download the latest package directly from package registry and they will not need to run git clone do all this staff with compilation

- instead pushing compiled libraries to PYPI/... we can push them back to github, so we will not need to compile them manually

- We can just move compiled libraries to Release page, but users will have to add it to path manually. So, they will have to download the latest release, unpack, add it to PATH environment variable for Windows, to LD_LIBRARY_PATH for Linux and even I don't know which environment variable is used for Mac. (Or we can force them to use specific env variable like BRAINFLOW_HOME)

- We can improve the previous option and develop some installer, which will just copy files and set environment variables, and users will still be able to install it manually. In this two options we can split releasing of shared library and bindings(As long as low level API keeps the same we can update compiled libraries without any changes in python\java\... or we are able to join them)

@daniellasry I think we should try to add Mac and 32bit libraries to our current worflow and if it's too uncomfortable for us we should consider options above
@conorrussomanno any inputs are highly welcome

**Comment by daniellasry** [comment]
Right now I don't know enough about Maven, CRAN, and brainflow to answer with confidence. Do Maven and CRAN provide package management, like PYPI does? Assuming yes, I'll give my general opinion:

**If someone clones the repository, I assume they want to compile from source.** I haven't seen any other library that requires you to clone the repository to get pre-compiled binaries.

I like your first solution: Java/Python/R developers can use brainflow without compiling by downloading poackages from Maven/PYPI/CRAN. (Alternatively, we can upload `.jar`, `python_package.zip`, and `r-package.zip` files to the releases tab).

C++ and C# developers can compile the .dll themselves. Since they are using brainflow in their own C++ or C# application, it's reasonable to assume they know how to install visual studio and build code. They're developers! (If we want to be nice, we can offer a `cpp-package.zip` and `csharp-package.zip` in the releases tab). We can leave it up to the individual developer to decide how they want to install the library in their project. They can copy it, or set LD_LIBRARY_PATH. Everyone's project is going to be different.

Nightly builds would be awesome, but maybe overkill. If we release manually every 1-2 months, that should be enough.

---

I hope this helps. I don't have as much experience dealing with multi-platform, multi-language libraries, so I might have missed something.

For now, I would choose whichever option is the least amount of work for us. brainflow is still in development. Not used by many people yet. Whatever method we choose, It's you and me who are going to suffer the consequences :) . Once we have more users, we can transition to a different release method.
